BeforeAll {
    # Nested 2-arg Join-Path: the 3-arg form is PS6+, and CI's windows job runs
    # Windows PowerShell 5.1. A literal '..\Install-Clipbridge.ps1' would also break
    # on Linux, where the backslash is part of the filename rather than a separator.
    $script:ScriptPath = Join-Path (Join-Path $PSScriptRoot '..') 'Install-Clipbridge.ps1'
    . $script:ScriptPath -DotSourceOnly
}

Describe 'Get-ClipbridgePaths' {
    It 'joins the ssh and config paths under the given directories' {
        $p = Get-ClipbridgePaths -SshDir '/home/x/.ssh' -ConfigDir '/home/x/.config/clipbridge'
        $p.SshConfigPath  | Should -Be (Join-Path '/home/x/.ssh' 'config')
        $p.ConfigJsonPath | Should -Be (Join-Path '/home/x/.config/clipbridge' 'config.json')
    }
}

Describe 'New-SshConfigBlock' {
    BeforeAll {
        $script:block = New-SshConfigBlock -HostAlias 'clipbridge' -TargetHost 'devsbx01' `
            -TargetUser 'vollmin' -IdentityFile '/home/x/.ssh/devsbx01_id_ed25519.pub'
    }

    It 'includes IdentitiesOnly yes - pins to a single identity out of ~27 agent keys' {
        $script:block | Should -Match 'IdentitiesOnly\s+yes'
    }
    It 'includes ForwardAgent no - clipbridge never authenticates onward' {
        $script:block | Should -Match 'ForwardAgent\s+no'
    }
    It 'names the Host alias' {
        $script:block | Should -Match 'Host\s+clipbridge'
    }
    It 'sets HostName to the real target' {
        $script:block | Should -Match 'HostName\s+devsbx01'
    }
    It 'sets User' {
        $script:block | Should -Match 'User\s+vollmin'
    }
    It 'points IdentityFile at the given (pre-existing devsbx01) key path' {
        $script:block | Should -Match ([regex]::Escape('IdentityFile /home/x/.ssh/devsbx01_id_ed25519.pub'))
    }
}

Describe 'Test-SshConfigHasHostBlock' {
    It 'returns $false on an empty config' {
        Test-SshConfigHasHostBlock -ExistingConfig '' -HostAlias 'clipbridge' | Should -BeFalse
    }
    It 'returns $false when the alias is absent' {
        $cfg = "Host github.com`n    User git`n"
        Test-SshConfigHasHostBlock -ExistingConfig $cfg -HostAlias 'clipbridge' | Should -BeFalse
    }
    It 'returns $true when the exact Host line is present' {
        $cfg = "Host github.com`n    User git`n`nHost clipbridge`n    HostName devsbx01`n"
        Test-SshConfigHasHostBlock -ExistingConfig $cfg -HostAlias 'clipbridge' | Should -BeTrue
    }
    It 'returns $true for a block generated by New-SshConfigBlock (idempotency, round trip)' {
        $block = New-SshConfigBlock -HostAlias 'clipbridge' -TargetHost 'devsbx01' `
            -TargetUser 'vollmin' -IdentityFile '/home/x/.ssh/devsbx01_id_ed25519.pub'
        Test-SshConfigHasHostBlock -ExistingConfig $block -HostAlias 'clipbridge' | Should -BeTrue
    }
    It 'tolerates leading whitespace before Host' {
        $cfg = "  Host clipbridge`n"
        Test-SshConfigHasHostBlock -ExistingConfig $cfg -HostAlias 'clipbridge' | Should -BeTrue
    }
    It 'does not false-positive on a Host alias that merely starts with the same name' {
        $cfg = "Host clipbridge-laptop`n    User someone`n"
        Test-SshConfigHasHostBlock -ExistingConfig $cfg -HostAlias 'clipbridge' | Should -BeFalse
    }
}

Describe 'New-ClipbridgeConfigObject' {
    It 'sets sshHost to the alias, not the real hostname' {
        $cfg = New-ClipbridgeConfigObject -HostAlias 'clipbridge' -Transport 'ssh'
        $cfg.sshHost | Should -Be 'clipbridge'
    }
    It 'carries the transport through' {
        $cfg = New-ClipbridgeConfigObject -HostAlias 'clipbridge' -Transport 'wsl'
        $cfg.transport | Should -Be 'wsl'
    }
    It 'rejects a transport outside ssh/wsl' {
        { New-ClipbridgeConfigObject -HostAlias 'clipbridge' -Transport 'carrier-pigeon' } | Should -Throw
    }
    It 'round-trips through JSON with the shape Send-Clip.ps1 expects' {
        $cfg = New-ClipbridgeConfigObject -HostAlias 'clipbridge' -Transport 'ssh'
        $round = $cfg | ConvertTo-Json | ConvertFrom-Json
        $round.sshHost   | Should -Be 'clipbridge'
        $round.transport | Should -Be 'ssh'
    }
}

Describe 'Get-SshProbeOutcome' {
    It 'reports ExeNotFound when the exe was not found' {
        Get-SshProbeOutcome -ExeFound $false | Should -Be 'ExeNotFound'
    }
    It 'reports Authenticated on a clean exit 0' {
        Get-SshProbeOutcome -ExeFound $true -ExitCode 0 -StdErr '' | Should -Be 'Authenticated'
    }
    It 'reports PermissionDenied when stderr says so' {
        Get-SshProbeOutcome -ExeFound $true -ExitCode 255 -StdErr 'user@devsbx01: Permission denied (publickey).' |
            Should -Be 'PermissionDenied'
    }
    It 'reports Timeout on a connection timeout' {
        Get-SshProbeOutcome -ExeFound $true -ExitCode 255 -StdErr 'ssh: connect to host devsbx01 port 22: Connection timed out' |
            Should -Be 'Timeout'
    }
    It 'reports OtherFailure for anything else' {
        Get-SshProbeOutcome -ExeFound $true -ExitCode 255 -StdErr 'ssh: Could not resolve hostname devsbx01: Name or service not known' |
            Should -Be 'OtherFailure'
    }
}

Describe 'Get-TransportFailureMessage' {
    It 'names the 1Password agent when both transports get Permission denied' {
        $msg = Get-TransportFailureMessage -SshOutcome 'PermissionDenied' -WslOutcome 'PermissionDenied' -TargetHost 'devsbx01'
        $msg | Should -Match '1Password'
        $msg | Should -Match 'ssh\.exe and wsl\.exe'
    }
    It 'still names the 1Password agent when only one transport got Permission denied, and names which one' {
        $msg = Get-TransportFailureMessage -SshOutcome 'PermissionDenied' -WslOutcome 'ExeNotFound' -TargetHost 'devsbx01'
        $msg | Should -Match '1Password'
        $msg | Should -Match '^ssh\.exe'
    }
    It 'names wsl.exe -e ssh specifically when that is the one denied' {
        $msg = Get-TransportFailureMessage -SshOutcome 'ExeNotFound' -WslOutcome 'PermissionDenied' -TargetHost 'devsbx01'
        $msg | Should -Match ([regex]::Escape('wsl.exe -e ssh'))
    }
    It 'reports a timeout distinctly, without blaming the 1Password agent' {
        $msg = Get-TransportFailureMessage -SshOutcome 'Timeout' -WslOutcome 'Timeout' -TargetHost 'devsbx01'
        $msg | Should -Match 'timed out'
        $msg | Should -Not -Match '1Password'
    }
    It 'reports both executables missing distinctly' {
        $msg = Get-TransportFailureMessage -SshOutcome 'ExeNotFound' -WslOutcome 'ExeNotFound' -TargetHost 'devsbx01'
        $msg | Should -Match 'PATH'
        $msg | Should -Not -Match '1Password'
    }
    It 'falls back to a generic message naming both outcomes for an unmatched combination' {
        $msg = Get-TransportFailureMessage -SshOutcome 'OtherFailure' -WslOutcome 'OtherFailure' -TargetHost 'devsbx01'
        $msg | Should -Match 'OtherFailure'
        $msg | Should -Match 'devsbx01'
    }
}

Describe 'Select-Transport' {
    It 'picks ssh when ssh authenticated' {
        Select-Transport -SshOutcome 'Authenticated' -WslOutcome 'NotProbed' -TargetHost 'devsbx01' | Should -Be 'ssh'
    }
    It 'picks wsl when ssh failed but wsl authenticated' {
        Select-Transport -SshOutcome 'PermissionDenied' -WslOutcome 'Authenticated' -TargetHost 'devsbx01' | Should -Be 'wsl'
    }
    It 'prefers ssh over wsl when both authenticate' {
        Select-Transport -SshOutcome 'Authenticated' -WslOutcome 'Authenticated' -TargetHost 'devsbx01' | Should -Be 'ssh'
    }
    It 'throws the locked-agent message when both are denied' {
        { Select-Transport -SshOutcome 'PermissionDenied' -WslOutcome 'PermissionDenied' -TargetHost 'devsbx01' } |
            Should -Throw -ExpectedMessage '*1Password*'
    }
}

Describe 'Invoke-TransportProbe parameter binding' {
    # This function spawns a process, so its I/O is not unit-testable -- but its
    # parameter CONTRACT is, and that is where the bug was. A nonexistent executable
    # returns at the Get-Command guard before anything is spawned, so this exercises
    # the bind and nothing else.
    It 'accepts an empty prefix, which is how ssh.exe is probed' {
        $r = Invoke-TransportProbe -Exe 'clipbridge-no-such-exe-9f3a' -Prefix @() -TargetHost 'nowhere.invalid'
        $r.ExeFound | Should -BeFalse
    }
    It 'accepts a populated prefix, which is how wsl.exe is probed' {
        $r = Invoke-TransportProbe -Exe 'clipbridge-no-such-exe-9f3a' -Prefix @('-e','ssh') -TargetHost 'nowhere.invalid'
        $r.ExeFound | Should -BeFalse
    }
}
